### ISSUE TITLE
Websocket Errs

### ISSUE THREAD

**Issue by bramses** [ixartz/Next-js-Boilerplate#305]
Hi! Great boilerplate, thank you. I seem to be getting websocket errors consistently and I'm not sure how to address it:

On the server:

```
Error handling upgrade request TypeError: Cannot read properties of undefined (reading 'bind')
    at DevServer.handleRequestImpl (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/base-server.js:478:50)
    at async /Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async handleRoute (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:305:33)
    at async resolveRoutes (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:525:28)
    at async upgradeHandler (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/lib/router-server.js:454:50)
    at async Server.<anonymous> (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/lib/start-server.js:170:13)
 GET /ws/069/odjxga5b/eventsource 404 in 62ms
 GET /ws/info?t=1725293484684 404 in 118ms
Error handling upgrade request TypeError: Cannot read properties of undefined (reading 'bind')
    at DevServer.handleRequestImpl (/Users/bram/Dropbox/PARA/Projects/ycb-companion/node_modules/next/dist/server/base-server.js:478:50)
 GET /ws/262/oti0xwhd/eventsource 404 in 89ms
 ```
 On the browser (using `npm run dev`):
 
 ```
 contentScript.bundle.js:10529 
        
        
       GET http://localhost:3000/ws/info?t=1725293622208 404 (Not Found)
```

EDIT: typo in title, I meant Websocket*

**Comment by bramses** [comment]
anything i should look at in particular?

**Comment by ixartz** [comment]
> anything i should look at in particular?

Unfortunately, the project doesn't use directly any websocket, it's probably some dependencies not working well.

**Comment by ixartz** [comment]
Any udpates?

**Comment by bramses** [comment]
I found a few issues: https://github.com/vercel/next.js/issues/55802 and https://github.com/vercel/next.js/discussions/68216 but I haven't found a fix yet that worked

**Comment by ixartz** [comment]
Thank you. Currently for now, I'm not able to reproduce it and it seems the issue is coming from Next.js.
